"""
This type stub file was generated by pyright.
"""

class I18nFileLoadError(Exception):
    def __init__(self, value) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    


class Loader:
    """Base class to load resources"""
    def __init__(self) -> None:
        ...
    
    def load_file(self, filename):
        ...
    
    def parse_file(self, file_content):
        ...
    
    def check_data(self, data, root_data): # -> bool:
        ...
    
    def get_data(self, data, root_data):
        ...
    
    def load_resource(self, filename, root_data):
        ...
    


