"""
This type stub file was generated by pyright.
"""

from .loader import Loader

class PythonLoader(Loader):
    """class to load python files"""
    def __init__(self) -> None:
        ...
    
    def load_file(self, filename): # -> Any:
        ...
    
    def parse_file(self, file_content):
        ...
    
    def check_data(self, data, root_data): # -> bool:
        ...
    
    def get_data(self, data, root_data): # -> Any:
        ...
    


