"""
This type stub file was generated by pyright.
"""

from .loader import Loader

class YamlLoader(Loader):
    """class to load yaml files"""
    def __init__(self) -> None:
        ...
    
    def parse_file(self, file_content): # -> Any:
        ...
    


