"""
This type stub file was generated by pyright.
"""

from . import config, resource_loader
from .resource_loader import I18nFileLoadError, load_config, register_loader
from .translator import t
from .translations import add as add_translation
from .config import get, set

load_path = ...
