"""
This type stub file was generated by pyright.
"""

container = ...
def add(key, value, locale=...): # -> None:
    ...

def has(key, locale=...): # -> bool:
    ...

def get(key, locale=...):
    ...

