"""
This type stub file was generated by pyright.
"""

from string import Template

class TranslationFormatter(Template):
    delimiter = ...
    def __init__(self, template) -> None:
        ...
    
    def format(self, **kwargs): # -> str:
        ...
    


def t(key, **kwargs): # -> str:
    ...

def translate(key, **kwargs): # -> str:
    ...

def pluralize(key, translation, count):
    ...

