"""
This type stub file was generated by pyright.
"""

import collections

logger = ...
def to_json(value): # -> str | Any | None:
    ...

def interpolate_str(template, **data):
    ...

def format_tag(tag_name, attributes, inner=..., closed=..., opened=...): # -> str:
    ...

def generate_hash(): # -> str:
    ...

def patch_collections_abc(member): # -> Any:
    ...

class AttributeDict(dict):
    """Dictionary subclass enabling attribute lookup/assignment of keys/values.

    For example::
        >>> m = AttributeDict({'foo': 'bar'})
        >>> m.foo
        'bar'
        >>> m.foo = 'not bar'
        >>> m['foo']
        'not bar'
    ``AttributeDict`` objects also provide ``.first()`` which acts like
    ``.get()`` but accepts multiple keys as arguments, and returns the value of
    the first hit, e.g.::
        >>> m = AttributeDict({'foo': 'bar', 'biz': 'baz'})
        >>> m.first('wrong', 'incorrect', 'foo', 'biz')
        'bar'
    """
    def __setattr__(self, key, value): # -> None:
        ...
    
    def __getattr__(self, key):
        ...
    
    def set_read_only(self, names, msg=...): # -> None:
        """
        Designate named attributes as read-only with the corresponding msg

        Method is additive. Making additional calls to this method will update
        existing messages and add to the current set of _read_only names.
        """
        ...
    
    def finalize(self, msg=...): # -> None:
        """Prevent any new keys being set."""
        ...
    
    def __setitem__(self, key, val): # -> None:
        ...
    
    def update(self, other): # -> None:
        ...
    
    def first(self, *names): # -> dict[Unknown, Unknown] | None:
        ...
    


def create_callback_id(output): # -> LiteralString:
    ...

def split_callback_id(callback_id): # -> list[Unknown] | dict[str, Unknown]:
    ...

def stringify_id(id_): # -> str:
    ...

def inputs_to_dict(inputs_list): # -> AttributeDict:
    ...

def convert_to_AttributeDict(nested_list): # -> list[Unknown]:
    ...

def inputs_to_vals(inputs): # -> list[list[Unknown] | Unknown]:
    ...

def run_command_with_process(cmd): # -> None:
    ...

def compute_md5(path): # -> str:
    ...

def job(msg=...): # -> (func: Unknown) -> ((*args: Unknown, **kwargs: Unknown) -> Unknown):
    ...

def gen_salt(chars): # -> str:
    ...

class OrderedSet(collections.abc.MutableSet):
    def __init__(self, *args) -> None:
        ...
    
    def add(self, value): # -> None:
        ...
    
    def discard(self, value): # -> None:
        ...
    
    def __contains__(self, x): # -> bool:
        ...
    
    def __len__(self): # -> int:
        ...
    
    def __iter__(self): # -> Generator[Unknown, None, None]:
        ...
    


def coerce_to_list(obj): # -> list[Unknown] | tuple[Unknown, ...]:
    ...

