NATION_DROPDOWN = "nation-dropdown"
SELECT_ALL_YEARS_BUTTON = "select-all-years-button"
YEAR_DROPDOWN = "year-dropdown"
MONTH_DROPDOWN = "month-dropdown"
BAR_CHART = "bar-chart"
SELECT_ALL_MONTHS_BUTTON = "select-all-months-button"
SELECT_ALL_CATEGORIES_BUTTON = "select-all-categories-button"
CATEGORY_DROPDOWN = "category-dropdown"
